project:
  type: book
  output-dir: docs

book:
  title: "AIRPACT6 Development"
  author: "Von P. Walden"
  date: last-modified
  chapters:
    - index.qmd
    - part: mcip-dev.qmd
    - part: smoke-dev.qmd
    - part: cmaq-dev.qmd
    - part: apptainer-dev.qmd
      chapters:
        - ubuntu.qmd
        - gnu_compilers.qmd
        - useful.qmd
        - openmpi.qmd
        - netcdf.qmd
    #    - airpact6.qmd
        - ioapi.qmd
    #    - mcip.qmd
        - cmaq.qmd
    #    - build_cmaq.qmd

format:
  html:
    theme: cosmo
