project:
  type: book

book:
  title: "AIRPACT6 Container Development"
  author: "Von P. Walden"
  date: last-modified
  chapters:
    - index.qmd
    - ubuntu.qmd
    - gnu_compilers.qmd
    - useful.qmd
    - openmpi.qmd
    - netcdf.qmd
#    - airpact6.qmd
    - ioapi.qmd
#    - mcip.qmd
    - cmaq.qmd
#    - build_cmaq.qmd

format:
  html:
    theme: cosmo
