project:
  type: website
  output-dir: docs

book:
  title: "AIRPACT6 Development Steps"
  author: "Von P. Walden"
  date: last-modified
  chapters:
    - index.qmd
    - hdf5.qmd
    - netcdf.qmd
#    - ioapi.qmd
#    - mcip.qmd

format:
  html:
    theme: cosmo
